"""initial_data_auth

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_areas")),
        sa.UniqueConstraint("name", name=op.f("uq_areas_name")),
    )
    op.create_table(
        "auth_throttles",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_auth_throttles")),
    )
    op.create_index(
        op.f("ix_auth_throttles_expires_at"),
        "auth_throttles",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "brigades",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brigades")),
        sa.UniqueConstraint("name", name=op.f("uq_brigades_name")),
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
    )
    op.create_table(
        "shifts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "end_at > start_at", name=op.f("ck_shifts_positive_interval")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shifts")),
    )
    op.create_index(op.f("ix_shifts_start_at"), "shifts", ["start_at"], unique=False)
    op.create_table(
        "work_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_codes")),
        sa.UniqueConstraint("code", name=op.f("uq_work_codes_code")),
    )
    op.create_table(
        "equipment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("area_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"], ["areas.id"], name=op.f("fk_equipment_area_id_areas")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment")),
    )
    op.create_index(
        op.f("ix_equipment_area_id"), "equipment", ["area_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("login", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("specialty", sa.String(length=128), nullable=True),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column("brigade_id", sa.Uuid(), nullable=True),
        sa.Column("shift_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "role IN ('master','worker','manager','admin')",
            name=op.f("ck_users_valid_role"),
        ),
        sa.ForeignKeyConstraint(
            ["brigade_id"],
            ["brigades.id"],
            name=op.f("fk_users_brigade_id_brigades"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
            name=op.f("fk_users_shift_id_shifts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("login", name=op.f("uq_users_login")),
    )
    op.create_index(op.f("ix_users_brigade_id"), "users", ["brigade_id"], unique=False)
    op.create_index(op.f("ix_users_shift_id"), "users", ["shift_id"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_auth_sessions")),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"),
        "auth_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "material_norms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("work_code_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_material_norms_positive_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_material_norms_equipment_id_equipment"),
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_material_norms_material_id_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["work_code_id"],
            ["work_codes.id"],
            name=op.f("fk_material_norms_work_code_id_work_codes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_norms")),
        sa.UniqueConstraint(
            "equipment_id",
            "work_code_id",
            "material_id",
            name=op.f("uq_material_norms_equipment_id"),
        ),
    )
    op.create_index(
        op.f("ix_material_norms_equipment_id"),
        "material_norms",
        ["equipment_id"],
        unique=False,
    )
    op.create_table(
        "user_areas",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("area_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
            name=op.f("fk_user_areas_area_id_areas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_areas_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "area_id", name=op.f("pk_user_areas")),
    )
    op.create_table(
        "work_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=64), nullable=False),
        sa.Column("work_type", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("area_id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("brigade_id", sa.Uuid(), nullable=True),
        sa.Column("responsible_id", sa.Uuid(), nullable=True),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("assignment_version", sa.Integer(), nullable=False),
        sa.Column("queue_position", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "priority IN ('emergency','high','normal','planned')",
            name=op.f("ck_work_orders_valid_priority"),
        ),
        sa.CheckConstraint(
            "status IN ('ISSUED','ACCEPTED','QUEUED','REJECTED','IN_PROGRESS','PAUSED','SUBMITTED','AI_REVIEW','REWORK','CLOSED','CANCELLED')",
            name=op.f("ck_work_orders_valid_status"),
        ),
        sa.CheckConstraint(
            "work_type IN ('planned','emergency')",
            name=op.f("ck_work_orders_valid_work_type"),
        ),
        sa.CheckConstraint(
            "(assignee_id IS NOT NULL AND brigade_id IS NULL AND responsible_id IS NULL) OR (assignee_id IS NULL AND brigade_id IS NOT NULL AND responsible_id IS NOT NULL)",
            name=op.f("ck_work_orders_one_assignment"),
        ),
        sa.CheckConstraint(
            "version > 0 AND assignment_version > 0",
            name=op.f("ck_work_orders_positive_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["area_id"], ["areas.id"], name=op.f("fk_work_orders_area_id_areas")
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"], ["users.id"], name=op.f("fk_work_orders_assignee_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["brigade_id"],
            ["brigades.id"],
            name=op.f("fk_work_orders_brigade_id_brigades"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_work_orders_equipment_id_equipment"),
        ),
        sa.ForeignKeyConstraint(
            ["master_id"], ["users.id"], name=op.f("fk_work_orders_master_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["responsible_id"],
            ["users.id"],
            name=op.f("fk_work_orders_responsible_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_orders")),
        sa.UniqueConstraint("number", name=op.f("uq_work_orders_number")),
    )
    op.create_index(
        op.f("ix_work_orders_area_id"), "work_orders", ["area_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_orders_assignee_id"), "work_orders", ["assignee_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_orders_brigade_id"), "work_orders", ["brigade_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_orders_due_at"), "work_orders", ["due_at"], unique=False
    )
    op.create_index(
        op.f("ix_work_orders_equipment_id"),
        "work_orders",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_orders_responsible_id"),
        "work_orders",
        ["responsible_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_orders_status"), "work_orders", ["status"], unique=False
    )
    op.create_table(
        "downtime_intervals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("work_order_id", sa.Uuid(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "end_at IS NULL OR end_at > start_at",
            name=op.f("ck_downtime_intervals_positive_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_downtime_intervals_equipment_id_equipment"),
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_downtime_intervals_work_order_id_work_orders"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_downtime_intervals")),
    )
    op.create_index(
        op.f("ix_downtime_intervals_equipment_id"),
        "downtime_intervals",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_downtime_intervals_work_order_id"),
        "downtime_intervals",
        ["work_order_id"],
        unique=False,
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("work_order_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("assignment_version", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.Uuid(), nullable=False),
        sa.Column("work_description", sa.Text(), nullable=False),
        sa.Column("work_code_id", sa.Uuid(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "revision > 0", name=op.f("ck_submissions_positive_revision")
        ),
        sa.ForeignKeyConstraint(
            ["work_code_id"],
            ["work_codes.id"],
            name=op.f("fk_submissions_work_code_id_work_codes"),
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_submissions_work_order_id_work_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"], ["users.id"], name=op.f("fk_submissions_worker_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submissions")),
        sa.UniqueConstraint(
            "work_order_id", "revision", name=op.f("uq_submissions_work_order_id")
        ),
    )
    op.create_index(
        op.f("ix_submissions_work_order_id"),
        "submissions",
        ["work_order_id"],
        unique=False,
    )
    op.create_table(
        "work_order_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("work_order_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("assignment_version", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_work_order_events_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_work_order_events_work_order_id_work_orders"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_order_events")),
    )
    op.create_index(
        op.f("ix_work_order_events_work_order_id"),
        "work_order_events",
        ["work_order_id"],
        unique=False,
    )
    op.create_table(
        "ai_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("order_version", sa.Integer(), nullable=False),
        sa.Column("assignment_version", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_ai_reviews_submission_id_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_reviews")),
        sa.UniqueConstraint("submission_id", name=op.f("uq_ai_reviews_submission_id")),
    )
    op.create_table(
        "master_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("work_order_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('accept','rework')",
            name=op.f("ck_master_decisions_valid_decision"),
        ),
        sa.CheckConstraint(
            "score IS NULL OR (score >= 0 AND score <= 100)",
            name=op.f("ck_master_decisions_valid_score"),
        ),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["users.id"],
            name=op.f("fk_master_decisions_master_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_master_decisions_submission_id_submissions"),
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_master_decisions_work_order_id_work_orders"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_master_decisions")),
    )
    op.create_index(
        op.f("ix_master_decisions_work_order_id"),
        "master_decisions",
        ["work_order_id"],
        unique=False,
    )
    op.create_table(
        "material_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_material_usage_positive_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_material_usage_material_id_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_material_usage_submission_id_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_usage")),
        sa.UniqueConstraint(
            "submission_id", "material_id", name=op.f("uq_material_usage_submission_id")
        ),
    )
    op.create_index(
        op.f("ix_material_usage_submission_id"),
        "material_usage",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("work_order_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "type IN ('before','after')", name=op.f("ck_photos_valid_type")
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_photos_submission_id_submissions"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_photos_uploaded_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_photos_work_order_id_work_orders"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photos")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_photos_storage_key")),
    )
    op.create_index(
        op.f("ix_photos_content_hash"), "photos", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_photos_submission_id"), "photos", ["submission_id"], unique=False
    )
    op.create_index(
        op.f("ix_photos_work_order_id"), "photos", ["work_order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_photos_work_order_id"), table_name="photos")
    op.drop_index(op.f("ix_photos_submission_id"), table_name="photos")
    op.drop_index(op.f("ix_photos_content_hash"), table_name="photos")
    op.drop_table("photos")
    op.drop_index(op.f("ix_material_usage_submission_id"), table_name="material_usage")
    op.drop_table("material_usage")
    op.drop_index(
        op.f("ix_master_decisions_work_order_id"), table_name="master_decisions"
    )
    op.drop_table("master_decisions")
    op.drop_table("ai_reviews")
    op.drop_index(
        op.f("ix_work_order_events_work_order_id"), table_name="work_order_events"
    )
    op.drop_table("work_order_events")
    op.drop_index(op.f("ix_submissions_work_order_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(
        op.f("ix_downtime_intervals_work_order_id"), table_name="downtime_intervals"
    )
    op.drop_index(
        op.f("ix_downtime_intervals_equipment_id"), table_name="downtime_intervals"
    )
    op.drop_table("downtime_intervals")
    op.drop_index(op.f("ix_work_orders_status"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_responsible_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_equipment_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_due_at"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_brigade_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_assignee_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_area_id"), table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_table("user_areas")
    op.drop_index(op.f("ix_material_norms_equipment_id"), table_name="material_norms")
    op.drop_table("material_norms")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_users_shift_id"), table_name="users")
    op.drop_index(op.f("ix_users_brigade_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_equipment_area_id"), table_name="equipment")
    op.drop_table("equipment")
    op.drop_table("work_codes")
    op.drop_index(op.f("ix_shifts_start_at"), table_name="shifts")
    op.drop_table("shifts")
    op.drop_table("materials")
    op.drop_table("brigades")
    op.drop_index(op.f("ix_auth_throttles_expires_at"), table_name="auth_throttles")
    op.drop_table("auth_throttles")
    op.drop_table("areas")
    # ### end Alembic commands ###
